# Wildtrax FEIS 2020 Image Dataset Ingestion

In [2]:
#from google.colab import drive
#drive.mount('/content/drive')

BASE_PATH = "C:/Users/ldick/Documents/Git/Data_607_project/"
#content/drive/MyDrive/Data607_Project/"

In [3]:
import pandas as pd

image_csv = BASE_PATH + "FEIS_Friends_of_Elk_Island_2020_image_report.csv"
df_image = pd.read_csv(image_csv)

print(df_image.shape)
print(df_image.columns.tolist())
df_image.head()

(203111, 22)
['project_id', 'location', 'location_id', 'image_id', 'image_date_time', 'source_file_name', 'equipment_make', 'equipment_model', 'equipment_serial', 'image_fire', 'image_nice', 'image_malfunction', 'image_set_id', 'image_fov', 'image_snow', 'image_snow_depth_m', 'image_water_depth_m', 'image_trigger_mode', 'image_is_blurred', 'media_url', 'image_in_wildtrax', 'image_comments']

,project_id,location,location_id,image_id,image_date_time,source_file_name,equipment_make,equipment_model,equipment_serial,image_fire,...,image_set_id,image_fov,image_snow,image_snow_depth_m,image_water_depth_m,image_trigger_mode,image_is_blurred,media_url,image_in_wildtrax,image_comments
0,354,FEIUCS-1,48436,31494483,2019-10-22 19:43:08,NaN,RECONYX,HC500 HYPERFIRE,H500HH03205516,False,...,10548,NaN,DNC,DNC,DNC,Motion Detection,f,https://wildtrax-cam-west.s3-accelerate.amazon...,t,NaN
1,354,FEIUCS-1,48436,31494482,2019-10-22 19:43:10,NaN,RECONYX,HC500 HYPERFIRE,H500HH03205516,False,...,10548,NaN,DNC,DNC,DNC,Motion Detection,f,https://wildtrax-cam-west.s3-accelerate.amazon...,t,NaN
2,354,FEIUCS-1,48436,31491575,2019-10-22 19:43:11,NaN,RECONYX,HC500 HYPERFIRE,H500HH03205516,False,...,10548,NaN,DNC,DNC,DNC,Motion Detection,f,https://wildtrax-cam-west.s3-accelerate.amazon...,t,NaN
3,354,FEIUCS-1,48436,31491573,2019-10-22 19:43:12,NaN,RECONYX,HC500 HYPERFIRE,H500HH03205516,False,...,10548,NaN,DNC,DNC,DNC,Motion Detection,f,https://wildtrax-cam-west.s3-accelerate.amazon...,t,NaN
4,354,FEIUCS-1,48436,31491574,2019-10-22 19:43:13,NaN,RECONYX,HC500 HYPERFIRE,H500HH03205516,False,...,10548,NaN,DNC,DNC,DNC,Motion Detection,f,https://wildtrax-cam-west.s3-accelerate.amazon...,t,NaN

In [4]:
tag_csv = BASE_PATH + "FEIS_Friends_of_Elk_Island_2020_tag_report.csv"
df_tag = pd.read_csv(tag_csv)

print(df_tag.shape)
print(df_tag.columns.tolist())
df_tag.head()

C:\Users\ldick\AppData\Local\Temp\ipykernel_56420\1646861977.py:2: DtypeWarning: Columns (0: tag_comments) have mixed types. Specify dtype option on import or set low_memory=False.
  df_tag = pd.read_csv(tag_csv)

(199585, 27)
['project_id', 'location', 'location_id', 'image_id', 'image_date_time', 'image_set_id', 'species_scientific_name', 'species_common_name', 'individual_count', 'age_class', 'sex_class', 'behaviours', 'health_diseases', 'coat_colours', 'coat_attributes', 'tine_attributes', 'direction_travel', 'has_collar', 'has_eartag', 'ihf', 'observer', 'observer_id', 'tag_comments', 'tag_needs_review', 'tag_is_verified', 'tag_id', 'species_class']

,project_id,location,location_id,image_id,image_date_time,image_set_id,species_scientific_name,species_common_name,individual_count,age_class,...,has_collar,has_eartag,ihf,observer,observer_id,tag_comments,tag_needs_review,tag_is_verified,tag_id,species_class
0,354,FEIUCS-1,48436,31494483,2019-10-22 19:43:08,10548,CERVUS CANADENSIS,Elk (wapiti),1,Adult,...,NaN,NaN,NaN,Jeremy Singh,553,NaN,f,t,16003104,Mammalia
1,354,FEIUCS-1,48436,31494482,2019-10-22 19:43:10,10548,CERVUS CANADENSIS,Elk (wapiti),1,Adult,...,NaN,NaN,NaN,Jeremy Singh,553,NaN,f,t,16003103,Mammalia
2,354,FEIUCS-1,48436,31491575,2019-10-22 19:43:11,10548,CERVUS CANADENSIS,Elk (wapiti),1,Adult,...,NaN,NaN,NaN,Jeremy Singh,553,NaN,f,t,16003102,Mammalia
3,354,FEIUCS-1,48436,31491573,2019-10-22 19:43:12,10548,NaN,NONE,VNA,VNA,...,NaN,NaN,NaN,Jeremy Singh,553,NaN,f,t,16003106,NaN
4,354,FEIUCS-1,48436,31491574,2019-10-22 19:43:13,10548,NaN,NONE,VNA,VNA,...,NaN,NaN,NaN,Jeremy Singh,553,NaN,f,t,16003107,NaN

In [5]:
df_image_small = df_image[[
    "image_id",
    "location",
    "location_id",
    "image_date_time",
    "media_url"
]]

df_tag_small = df_tag[[
    "image_id",
    "species_common_name",
    "age_class",
    "sex_class"
]]

In [6]:
df_merged = pd.merge(df_image_small, df_tag_small, on="image_id", how="inner")

In [7]:
print(df_merged.shape)
df_merged.head()

(199585, 8)

,image_id,location,location_id,image_date_time,media_url,species_common_name,age_class,sex_class
0,31494483,FEIUCS-1,48436,2019-10-22 19:43:08,https://wildtrax-cam-west.s3-accelerate.amazon...,Elk (wapiti),Adult,Unkn
1,31494482,FEIUCS-1,48436,2019-10-22 19:43:10,https://wildtrax-cam-west.s3-accelerate.amazon...,Elk (wapiti),Adult,Unkn
2,31491575,FEIUCS-1,48436,2019-10-22 19:43:11,https://wildtrax-cam-west.s3-accelerate.amazon...,Elk (wapiti),Adult,Unkn
3,31491573,FEIUCS-1,48436,2019-10-22 19:43:12,https://wildtrax-cam-west.s3-accelerate.amazon...,NONE,VNA,VNA
4,31491574,FEIUCS-1,48436,2019-10-22 19:43:13,https://wildtrax-cam-west.s3-accelerate.amazon...,NONE,VNA,VNA

In [8]:
df_merged["species_common_name"].value_counts().head(20)

species_common_name
Elk (wapiti)           74345
NONE                   44425
Bison                  37731
White-tailed Deer      18077
Moose                  14890
Coyote                  3934
Snowshoe Hare           2919
STAFF/SETUP             1559
Mule Deer                585
Unidentified             375
Human                    201
Fisher                   108
Songbird                  93
Red Squirrel              69
Bird                      67
Gray Wolf                 50
Wild Boar                 48
Black Bear                28
Porcupine                 18
Ducks, Swans, Geese       17
Name: count, dtype: int64

##Data Cleaning

In [10]:
df_clean = df_merged.copy()

#Removing bad labels
df_clean = df_clean.dropna(subset=["species_common_name"])
df_clean = df_clean[df_clean["species_common_name"] != "NONE"]
df_clean = df_clean[df_clean["species_common_name"] != "STAFF/SETUP"]
df_clean = df_clean[df_clean["species_common_name"] != "Unidentified"]

#Removing bad URLS(but there weren't any for this dataset)
df_clean = df_clean.dropna(subset=["media_url"])

print(df_clean.shape)
df_clean["species_common_name"].value_counts().head(20)

(153226, 8)

species_common_name
Elk (wapiti)                74345
Bison                       37731
White-tailed Deer           18077
Moose                       14890
Coyote                       3934
Snowshoe Hare                2919
Mule Deer                     585
Human                         201
Fisher                        108
Songbird                       93
Red Squirrel                   69
Bird                           67
Gray Wolf                      50
Wild Boar                      48
Black Bear                     28
Porcupine                      18
Ducks, Swans, Geese            17
Domestic Dog                   16
All Terrain Vehicle            14
Domestic Cat (House Cat)        9
Name: count, dtype: int64

In [11]:
#Selecting species
selected_species = [
    "Elk (wapiti)",
    "Bison",
    "White-tailed Deer",
    "Moose",
    "Coyote",
    "Snowshoe Hare"
]

df_project = df_clean[df_clean["species_common_name"].isin(selected_species)].copy()

print(df_project.shape)
print(df_project["species_common_name"].value_counts())

(151896, 8)
species_common_name
Elk (wapiti)         74345
Bison                37731
White-tailed Deer    18077
Moose                14890
Coyote                3934
Snowshoe Hare         2919
Name: count, dtype: int64

##Downloading Images

In [13]:
#Picked 300 per sample for initial testing purpose
n_per_class = 300

df_sampled = (
    df_project
    .groupby("species_common_name", group_keys=True)
    .apply(lambda x: x.sample(n=n_per_class, random_state=42))
    .reset_index(drop=False)
    .drop("level_1", axis=1)
)

print(df_sampled.shape)
print(df_sampled.head())
print(df_sampled["species_common_name"].value_counts())

(1800, 8)
  species_common_name  image_id   location  location_id       image_date_time  \
0               Bison  31553939  FEIUCS-23        49099   2020-03-31 15:24:21
1               Bison  31584779  FEIUCS-36        48413   2020-04-28 04:00:56
2               Bison  31513122   FEIUCS-4        48410   2020-05-15 08:00:10
3               Bison  32755756  FEIUCS-30        48417   2020-07-11 21:43:57
4               Bison  32767060  FEIUCS-30        48417   2019-10-31 10:30:51

                                           media_url age_class sex_class
0  https://wildtrax-cam-west.s3-accelerate.amazon...     Adult    Female
1  https://wildtrax-cam-west.s3-accelerate.amazon...     Adult      Unkn
2  https://wildtrax-cam-west.s3-accelerate.amazon...     Adult      Male
3  https://wildtrax-cam-west.s3-accelerate.amazon...       Juv      Unkn
4  https://wildtrax-cam-west.s3-accelerate.amazon...     Adult      Unkn
species_common_name
Bison                300
Coyote               300
Elk (wapiti)         300
Moose                300
Snowshoe Hare        300
White-tailed Deer    300
Name: count, dtype: int64

In [14]:
df_sampled["age_class"].value_counts()

age_class
Adult    1749
Juv        51
Name: count, dtype: int64

In [15]:
df_sampled["sex_class"].value_counts()

sex_class
Unkn      1299
Male       379
Female     122
Name: count, dtype: int64

In [16]:
#Making filepath so that dataframe becomes the source of truth(label)
all_images_path = BASE_PATH + "all_images"

df_sampled["filepath"] = df_sampled["image_id"].astype(str).apply(
    lambda x: all_images_path + x + ".jpg"
)

In [17]:
df_sampled.to_csv(BASE_PATH + "dataset_labels.csv", index=False)

In [18]:
import os
os.makedirs(all_images_path, exist_ok=True)
print(all_images_path)

C:/Users/ldick/Documents/Git/Data_607_project/all_images

In [19]:
print(df_sampled.head())

  species_common_name  image_id   location  location_id       image_date_time  \
0               Bison  31553939  FEIUCS-23        49099   2020-03-31 15:24:21
1               Bison  31584779  FEIUCS-36        48413   2020-04-28 04:00:56
2               Bison  31513122   FEIUCS-4        48410   2020-05-15 08:00:10
3               Bison  32755756  FEIUCS-30        48417   2020-07-11 21:43:57
4               Bison  32767060  FEIUCS-30        48417   2019-10-31 10:30:51

                                           media_url age_class sex_class  \
0  https://wildtrax-cam-west.s3-accelerate.amazon...     Adult    Female
1  https://wildtrax-cam-west.s3-accelerate.amazon...     Adult      Unkn
2  https://wildtrax-cam-west.s3-accelerate.amazon...     Adult      Male
3  https://wildtrax-cam-west.s3-accelerate.amazon...       Juv      Unkn
4  https://wildtrax-cam-west.s3-accelerate.amazon...     Adult      Unkn

                                            filepath
0  C:/Users/ldick/Documents/Git/Data_607_project/...
1  C:/Users/ldick/Documents/Git/Data_607_project/...
2  C:/Users/ldick/Documents/Git/Data_607_project/...
3  C:/Users/ldick/Documents/Git/Data_607_project/...
4  C:/Users/ldick/Documents/Git/Data_607_project/...

In [ ]:
import requests

success = 0
failed = 0

for i, row in df_sampled.iterrows():
    url = row["media_url"]
    image_id = row["image_id"]

    save_path = all_images_path + "/" + str(image_id) + ".jpg"
    
    try:
        r = requests.get(url)

        if r.status_code == 200:
            with open(save_path, "wb") as f:
                print(i)
                f.write(r.content)
                print(save_path)
            success += 1
        else:
            print("Failed:", image_id)
            failed += 1

    except:
        print("Error:", image_id)
        failed += 1

print("Downloaded:", success)
print("Failed:", failed)

0
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31553939.jpg
1
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31584779.jpg
2
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31513122.jpg
3
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755756.jpg
4
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32767060.jpg
5
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31619982.jpg
6
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32761847.jpg
7
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31655200.jpg
8
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31624080.jpg
9
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31646442.jpg
10
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755499.jpg
11
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31646482.jpg
12
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31600992.jpg
13
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32759274.jpg
14
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32759366.jpg
15
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762804.jpg
16
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31530620.jpg
17
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32767384.jpg
18
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32760630.jpg
19
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755329.jpg
20
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755781.jpg
21
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755753.jpg
22
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31495778.jpg
23
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31633897.jpg
24
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31620196.jpg
25
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32754694.jpg
26
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31645506.jpg
27
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32767036.jpg
28
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32773904.jpg
29
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32768311.jpg
30
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32768055.jpg
31
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762557.jpg
32
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31570405.jpg
33
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31569872.jpg
34
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31531786.jpg
35
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31617403.jpg
36
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32775429.jpg
37
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32773055.jpg
38
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31578719.jpg
39
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32771555.jpg
40
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31530689.jpg
41
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32767025.jpg
42
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31569330.jpg
43
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762255.jpg
44
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32757572.jpg
45
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31615862.jpg
46
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32754652.jpg
47
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32765839.jpg
48
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31620195.jpg
49
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32760509.jpg
50
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32767822.jpg
51
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31672722.jpg
52
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32773785.jpg
53
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31614144.jpg
54
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31613999.jpg
55
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32775659.jpg
56
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32760722.jpg
57
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755811.jpg
58
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32767792.jpg
59
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32760547.jpg
60
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32774269.jpg
61
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32754630.jpg
62
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32775711.jpg
63
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32766357.jpg
64
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32770652.jpg
65
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762922.jpg
66
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32772704.jpg
67
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31559495.jpg
68
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32768221.jpg
69
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32766003.jpg
70
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31646474.jpg
71
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32754607.jpg
72
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31587328.jpg
73
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32754689.jpg
74
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31584411.jpg
75
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32769878.jpg
76
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755493.jpg
77
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755824.jpg
78
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32772308.jpg
79
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31551893.jpg
80
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755063.jpg
81
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32773753.jpg
82
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31532618.jpg
83
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762697.jpg
84
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32772925.jpg
85
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32759095.jpg
86
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31533291.jpg
87
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32768670.jpg
88
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31585885.jpg
89
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32769709.jpg
90
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31553737.jpg
91
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32772929.jpg
92
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31551974.jpg
93
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32770533.jpg
94
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31620210.jpg
95
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32757122.jpg
96
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31556902.jpg
97
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755529.jpg
98
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32770801.jpg
99
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32758842.jpg
100
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31600937.jpg
101
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32765031.jpg
102
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32759055.jpg
103
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32756002.jpg
104
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31569433.jpg
105
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32769565.jpg
106
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31513111.jpg
107
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755069.jpg
108
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755142.jpg
109
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32765312.jpg
110
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31620065.jpg
111
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755362.jpg
112
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32774129.jpg
113
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32767244.jpg
114
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32775217.jpg
115
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32766455.jpg
116
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31581468.jpg
117
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32757686.jpg
118
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31649138.jpg
119
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32758815.jpg
120
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31581914.jpg
121
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32766146.jpg
122
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32761333.jpg
123
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762158.jpg
124
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32760463.jpg
125
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32758287.jpg
126
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31677038.jpg
127
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31568636.jpg
128
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32761078.jpg
129
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32772049.jpg
130
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31570674.jpg
131
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32769891.jpg
132
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32760408.jpg
133
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755765.jpg
134
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31648793.jpg
135
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31568348.jpg
136
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31564247.jpg
137
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32772335.jpg
138
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32764341.jpg
139
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31580195.jpg
140
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32772973.jpg
141
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31620282.jpg
142
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31614121.jpg
143
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31570455.jpg
144
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32760650.jpg
145
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32766769.jpg
146
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32766791.jpg
147
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31598456.jpg
148
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31620080.jpg
149
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32772417.jpg
150
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31558627.jpg
151
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31613711.jpg
152
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31601908.jpg
153
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31571207.jpg
154
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31585995.jpg
155
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32773337.jpg
156
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31584464.jpg
157
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32767773.jpg
158
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32760228.jpg
159
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31548428.jpg
160
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31620008.jpg
161
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31553219.jpg
162
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32770223.jpg
163
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32754851.jpg
164
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32774871.jpg
165
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762837.jpg
166
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31646493.jpg
167
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31548468.jpg
168
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32771235.jpg
169
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31548423.jpg
170
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31569021.jpg
171
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32760979.jpg
172
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32775967.jpg
173
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32761629.jpg
174
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32768794.jpg
175
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32771249.jpg
176
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31552086.jpg
177
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32765595.jpg
178
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32775381.jpg
179
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32764994.jpg
180
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762739.jpg
181
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32773061.jpg
182
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32772909.jpg
183
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31646547.jpg
184
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32761921.jpg
185
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31610904.jpg
186
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32758539.jpg
187
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31592928.jpg
188
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755681.jpg
189
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755517.jpg
190
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32764022.jpg
191
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31591751.jpg
192
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31584216.jpg
193
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31533394.jpg
194
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32769182.jpg
195
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32768756.jpg
196
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32768323.jpg
197
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31645306.jpg
198
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32758719.jpg
199
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32757276.jpg
200
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31571266.jpg
201
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32761057.jpg
202
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31570431.jpg
203
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31560602.jpg
204
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31585005.jpg
205
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32768216.jpg
206
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31670768.jpg
207
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32764654.jpg
208
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31670541.jpg
209
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32756816.jpg
210
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31560416.jpg
211
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31559145.jpg
212
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31559963.jpg
213
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31615616.jpg
214
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32773402.jpg
215
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31538520.jpg
216
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31581774.jpg
217
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32758122.jpg
218
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32765895.jpg
219
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762101.jpg
220
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32767584.jpg
221
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31558954.jpg
222
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32775366.jpg
223
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32768256.jpg
224
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32758182.jpg
225
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32769658.jpg
226
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32759585.jpg
227
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32775343.jpg
228
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32764961.jpg
229
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31569273.jpg
230
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32769955.jpg
231
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32760922.jpg
232
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32758479.jpg
233
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31580216.jpg
234
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32765623.jpg
235
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32773613.jpg
236
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32754860.jpg
237
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762600.jpg
238
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31558536.jpg
239
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32756025.jpg
240
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32766324.jpg
241
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762705.jpg
242
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32775966.jpg
243
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32773000.jpg
244
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31511760.jpg
245
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32760976.jpg
246
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32754886.jpg
247
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32759149.jpg
248
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32763436.jpg
249
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32774409.jpg
250
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32773040.jpg
251
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31670082.jpg
252
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32773184.jpg
253
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31658582.jpg
254
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755950.jpg
255
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32767473.jpg
256
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32765160.jpg
257
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32761699.jpg
258
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32758795.jpg
259
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32765300.jpg
260
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31512938.jpg
261
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31620147.jpg
262
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32763170.jpg
263
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32762756.jpg
264
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32759367.jpg
265
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32771265.jpg
266
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32763903.jpg
267
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32755462.jpg
268
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31568354.jpg
269
C:/Users/ldick/Documents/Git/Data_607_project/all_images/32757109.jpg
270
C:/Users/ldick/Documents/Git/Data_607_project/all_images/31591713.jpg
271